services:

  app:
    container_name: app
    build: .
    ports:
      - "3838:3838"
    env_file:
      - .env
    volumes:
      - ./shiny-app:/srv/app
    depends_on:
      - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  db:
    container_name: db
    build: ./postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
    volumes:
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/var/www/certbot
    depends_on:
      - app
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

  certbot:
    container_name: certbot
    image: certbot/certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email lizzy@eclipsegeomatics.com --agree-tos --no-eff-email -d restoration.skeenasalmon.info -d www.restoration.skeenasalmon.info -v
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/var/www/certbot
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
