proxy_cache_path /tmp/nginx_cache levels=1:2 keys_zone=cache:30m max_size=250m;
proxy_temp_path /tmp/nginx_proxy 1 2;

# nginx settings with ssl
server {
    listen 443 ssl;
    server_name restoration.skeenasalmon.info;

    ssl_certificate /etc/nginx/ssl/live/restoration.skeenasalmon.info/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/restoration.skeenasalmon.info/privkey.pem;

    ssl_session_cache builtin:1000 shared:SSL:10m;
    ssl_protocols TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_prefer_server_ciphers on;

    gzip on;
    gzip_types text/plain application/javascript application/x-javascript text/xml text/css;
    gzip_min_length 1000;

    location / {
        proxy_pass http://app:3838/;
        proxy_ssl_server_name on;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_cache cache;
        proxy_cache_bypass $cookie_auth_tkt;
        proxy_no_cache $cookie_auth_tkt;
        proxy_cache_valid 30m;
        proxy_cache_key $host$scheme$proxy_host$request_uri;
        
        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;

        # webSocket support -- fix error
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        
        # ssl certificates for upstream
        proxy_ssl_certificate /etc/nginx/ssl/live/restoration.skeenasalmon.info-0001/fullchain.pem;
        proxy_ssl_certificate_key /etc/nginx/ssl/live/restoration.skeenasalmon.info-0001/privkey.pem;
    }

    location ~ /.well-known/acme-challenge/ {
        allow all;
        root /var/www/certbot;
    }
}

# http to https redir
server {
    listen 80;
    server_name restoration.skeenasalmon.info www.restoration.skeenasalmon.info;

    location /.well-known/acme-challenge/ {
        allow all;
        root /var/www/certbot;
    }
}
